# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/illidan/file/cppfile/firstProject/sylar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/illidan/file/cppfile/firstProject/sylar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/illidan/file/cppfile/firstProject/sylar/CMakeFiles /home/illidan/file/cppfile/firstProject/sylar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/illidan/file/cppfile/firstProject/sylar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named sylar

# Build rule for target.
sylar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sylar
.PHONY : sylar

# fast build rule for target.
sylar/fast:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/build
.PHONY : sylar/fast

#=============================================================================
# Target rules for targets named text_config

# Build rule for target.
text_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 text_config
.PHONY : text_config

# fast build rule for target.
text_config/fast:
	$(MAKE) -f CMakeFiles/text_config.dir/build.make CMakeFiles/text_config.dir/build
.PHONY : text_config/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

config.o: config.cc.o

.PHONY : config.o

# target to build an object file
config.cc.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/config.cc.o
.PHONY : config.cc.o

config.i: config.cc.i

.PHONY : config.i

# target to preprocess a source file
config.cc.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/config.cc.i
.PHONY : config.cc.i

config.s: config.cc.s

.PHONY : config.s

# target to generate assembly for a file
config.cc.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/config.cc.s
.PHONY : config.cc.s

fiber.o: fiber.cc.o

.PHONY : fiber.o

# target to build an object file
fiber.cc.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/fiber.cc.o
.PHONY : fiber.cc.o

fiber.i: fiber.cc.i

.PHONY : fiber.i

# target to preprocess a source file
fiber.cc.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/fiber.cc.i
.PHONY : fiber.cc.i

fiber.s: fiber.cc.s

.PHONY : fiber.s

# target to generate assembly for a file
fiber.cc.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/fiber.cc.s
.PHONY : fiber.cc.s

log.o: log.cc.o

.PHONY : log.o

# target to build an object file
log.cc.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/log.cc.o
.PHONY : log.cc.o

log.i: log.cc.i

.PHONY : log.i

# target to preprocess a source file
log.cc.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/log.cc.i
.PHONY : log.cc.i

log.s: log.cc.s

.PHONY : log.s

# target to generate assembly for a file
log.cc.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/log.cc.s
.PHONY : log.cc.s

scheduler.o: scheduler.cc.o

.PHONY : scheduler.o

# target to build an object file
scheduler.cc.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/scheduler.cc.o
.PHONY : scheduler.cc.o

scheduler.i: scheduler.cc.i

.PHONY : scheduler.i

# target to preprocess a source file
scheduler.cc.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/scheduler.cc.i
.PHONY : scheduler.cc.i

scheduler.s: scheduler.cc.s

.PHONY : scheduler.s

# target to generate assembly for a file
scheduler.cc.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/scheduler.cc.s
.PHONY : scheduler.cc.s

test.o: test.cc.o

.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i

.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s

.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.s
.PHONY : test.cc.s

test_fiber.o: test_fiber.cc.o

.PHONY : test_fiber.o

# target to build an object file
test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/test_fiber.cc.o
.PHONY : test_fiber.cc.o

test_fiber.i: test_fiber.cc.i

.PHONY : test_fiber.i

# target to preprocess a source file
test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/test_fiber.cc.i
.PHONY : test_fiber.cc.i

test_fiber.s: test_fiber.cc.s

.PHONY : test_fiber.s

# target to generate assembly for a file
test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/test_fiber.cc.s
.PHONY : test_fiber.cc.s

test_scheduler.o: test_scheduler.cc.o

.PHONY : test_scheduler.o

# target to build an object file
test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/test_scheduler.cc.o
.PHONY : test_scheduler.cc.o

test_scheduler.i: test_scheduler.cc.i

.PHONY : test_scheduler.i

# target to preprocess a source file
test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/test_scheduler.cc.i
.PHONY : test_scheduler.cc.i

test_scheduler.s: test_scheduler.cc.s

.PHONY : test_scheduler.s

# target to generate assembly for a file
test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/test_scheduler.cc.s
.PHONY : test_scheduler.cc.s

test_thread.o: test_thread.cc.o

.PHONY : test_thread.o

# target to build an object file
test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/test_thread.cc.o
.PHONY : test_thread.cc.o

test_thread.i: test_thread.cc.i

.PHONY : test_thread.i

# target to preprocess a source file
test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/test_thread.cc.i
.PHONY : test_thread.cc.i

test_thread.s: test_thread.cc.s

.PHONY : test_thread.s

# target to generate assembly for a file
test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/test_thread.cc.s
.PHONY : test_thread.cc.s

test_util.o: test_util.cc.o

.PHONY : test_util.o

# target to build an object file
test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/test_util.cc.o
.PHONY : test_util.cc.o

test_util.i: test_util.cc.i

.PHONY : test_util.i

# target to preprocess a source file
test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/test_util.cc.i
.PHONY : test_util.cc.i

test_util.s: test_util.cc.s

.PHONY : test_util.s

# target to generate assembly for a file
test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/test_util.cc.s
.PHONY : test_util.cc.s

text_config.o: text_config.cc.o

.PHONY : text_config.o

# target to build an object file
text_config.cc.o:
	$(MAKE) -f CMakeFiles/text_config.dir/build.make CMakeFiles/text_config.dir/text_config.cc.o
.PHONY : text_config.cc.o

text_config.i: text_config.cc.i

.PHONY : text_config.i

# target to preprocess a source file
text_config.cc.i:
	$(MAKE) -f CMakeFiles/text_config.dir/build.make CMakeFiles/text_config.dir/text_config.cc.i
.PHONY : text_config.cc.i

text_config.s: text_config.cc.s

.PHONY : text_config.s

# target to generate assembly for a file
text_config.cc.s:
	$(MAKE) -f CMakeFiles/text_config.dir/build.make CMakeFiles/text_config.dir/text_config.cc.s
.PHONY : text_config.cc.s

thread.o: thread.cc.o

.PHONY : thread.o

# target to build an object file
thread.cc.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/thread.cc.o
.PHONY : thread.cc.o

thread.i: thread.cc.i

.PHONY : thread.i

# target to preprocess a source file
thread.cc.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/thread.cc.i
.PHONY : thread.cc.i

thread.s: thread.cc.s

.PHONY : thread.s

# target to generate assembly for a file
thread.cc.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/thread.cc.s
.PHONY : thread.cc.s

util.o: util.cc.o

.PHONY : util.o

# target to build an object file
util.cc.o:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/util.cc.o
.PHONY : util.cc.o

util.i: util.cc.i

.PHONY : util.i

# target to preprocess a source file
util.cc.i:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/util.cc.i
.PHONY : util.cc.i

util.s: util.cc.s

.PHONY : util.s

# target to generate assembly for a file
util.cc.s:
	$(MAKE) -f CMakeFiles/sylar.dir/build.make CMakeFiles/sylar.dir/util.cc.s
.PHONY : util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_scheduler"
	@echo "... test"
	@echo "... sylar"
	@echo "... text_config"
	@echo "... test_thread"
	@echo "... test_util"
	@echo "... test_fiber"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... fiber.o"
	@echo "... fiber.i"
	@echo "... fiber.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... scheduler.o"
	@echo "... scheduler.i"
	@echo "... scheduler.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... test_fiber.o"
	@echo "... test_fiber.i"
	@echo "... test_fiber.s"
	@echo "... test_scheduler.o"
	@echo "... test_scheduler.i"
	@echo "... test_scheduler.s"
	@echo "... test_thread.o"
	@echo "... test_thread.i"
	@echo "... test_thread.s"
	@echo "... test_util.o"
	@echo "... test_util.i"
	@echo "... test_util.s"
	@echo "... text_config.o"
	@echo "... text_config.i"
	@echo "... text_config.s"
	@echo "... thread.o"
	@echo "... thread.i"
	@echo "... thread.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

